version: '3.8'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: adonis
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5535:5432" # Mapeo del puerto 5432

volumes:
  pgdata:
